# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-S3
version:      0.04
version_from: lib/Apache2/S3.pm
installdirs:  site
requires:
    Digest::HMAC:                  0
    Digest::SHA1:                  0
    HTML::Entities:                0
    MIME::Base64:                  0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
